<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // Electronics Category (ID: 1) - 7 products
            [
                'name' => 'Apple iPhone 15 Pro Max',
                'slug' => 'apple-iphone-15-pro-max',
                'description' => 'Latest iPhone with A17 Pro chip, titanium design, and advanced camera system',
                'price' => 1199.00,
                'purchase_price' => 750.00,
                'discount_price' => 1099.00,
                'stock' => 50,
                'sold_count' => 245,
                'rating' => 4.8,
                'featured' => true,
                'is_best_selling' => true,
                'is_latest' => true,
                'is_flash_sale' => false,
                'is_todays_deal' => true,
                'image' => 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=500',
                'category_id' => 1,
            ],
            [
                'name' => 'Samsung Galaxy S24 Ultra',
                'slug' => 'samsung-galaxy-s24-ultra',
                'description' => 'Premium Android flagship with S Pen, 200MP camera, and AI features',
                'price' => 1299.00,
                'purchase_price' => 800.00,
                'discount_price' => 1199.00,
                'stock' => 40,
                'sold_count' => 189,
                'rating' => 4.7,
                'featured' => true,
                'is_best_selling' => true,
                'is_latest' => true,
                'is_flash_sale' => true,
                'is_todays_deal' => false,
                'image' => 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500',
                'category_id' => 1,
            ],
            [
                'name' => 'Sony WH-1000XM5 Headphones',
                'slug' => 'sony-wh-1000xm5-headphones',
                'description' => 'Industry-leading noise canceling wireless headphones',
                'price' => 399.00,
                'purchase_price' => 240.00,
                'discount_price' => 329.00,
                'stock' => 80,
                'sold_count' => 412,
                'rating' => 4.9,
                'featured' => true,
                'is_best_selling' => true,
                'is_latest' => false,
                'is_flash_sale' => false,
                'is_todays_deal' => true,
                'image' => 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=500',
                'category_id' => 1,
            ],
            [
                'name' => 'Apple MacBook Pro 14" M3',
                'slug' => 'apple-macbook-pro-14-m3',
                'description' => 'Powerful laptop with M3 chip, Liquid Retina XDR display',
                'price' => 1999.00,
                'purchase_price' => 1200.00,
                'discount_price' => 1849.00,
                'stock' => 25,
                'sold_count' => 156,
                'rating' => 4.9,
                'featured' => true,
                'is_best_selling' => false,
                'is_latest' => true,
                'is_flash_sale' => false,
                'is_todays_deal' => false,
                'image' => 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500',
                'category_id' => 1,
            ],
            [
                'name' => 'DJI Mini 4 Pro Drone',
                'slug' => 'dji-mini-4-pro-drone',
                'description' => 'Lightweight drone with 4K camera and intelligent flight modes',
                'price' => 759.00,
                'purchase_price' => 450.00,
                'discount_price' => 699.00,
                'stock' => 35,
                'sold_count' => 98,
                'rating' => 4.6,
                'featured' => false,
                'is_best_selling' => false,
                'is_latest' => true,
                'is_flash_sale' => true,
                'is_todays_deal' => true,
                'image' => 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=500',
                'category_id' => 1,
            ],
            [
                'name' => 'Apple Watch Series 9',
                'slug' => 'apple-watch-series-9',
                'description' => 'Advanced smartwatch with health tracking and fitness features',
                'price' => 429.00,
                'purchase_price' => 260.00,
                'discount_price' => 379.00,
                'stock' => 60,
                'sold_count' => 287,
                'rating' => 4.7,
                'featured' => true,
                'is_best_selling' => true,
                'is_latest' => true,
                'is_flash_sale' => false,
                'is_todays_deal' => true,
                'image' => 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=500',
                'category_id' => 1,
            ],
            [
                'name' => 'iPad Air 11" M2',
                'slug' => 'ipad-air-11-m2',
                'description' => 'Versatile tablet with M2 chip and Apple Pencil support',
                'price' => 599.00,
                'purchase_price' => 360.00,
                'discount_price' => 549.00,
                'stock' => 45,
                'sold_count' => 203,
                'rating' => 4.8,
                'featured' => false,
                'is_best_selling' => true,
                'is_latest' => true,
                'is_flash_sale' => false,
                'is_todays_deal' => false,
                'image' => 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500',
                'category_id' => 1,
            ],

            // Computers Category (ID: 2) - 6 products
            [
                'name' => 'Dell XPS 15 Laptop',
                'slug' => 'dell-xps-15-laptop',
                'description' => 'Premium laptop with Intel i9, 32GB RAM, 4K OLED display',
                'price' => 2299.00,
                'purchase_price' => 1400.00,
                'discount_price' => 1999.00,
                'stock' => 20,
                'sold_count' => 87,
                'rating' => 4.7,
                'featured' => true,
                'is_best_selling' => false,
                'is_latest' => true,
                'is_flash_sale' => true,
                'is_todays_deal' => false,
                'image' => 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=500',
                'category_id' => 2,
            ],
            [
                'name' => 'Gaming PC RTX 4080',
                'slug' => 'gaming-pc-rtx-4080',
                'description' => 'High-end gaming desktop with RTX 4080, Ryzen 9, RGB lighting',
                'price' => 2899.00,
                'purchase_price' => 1750.00,
                'discount_price' => 2599.00,
                'stock' => 15,
                'sold_count' => 65,
                'rating' => 4.9,
                'featured' => true,
                'is_best_selling' => true,
                'is_latest' => true,
                'is_flash_sale' => false,
                'is_todays_deal' => true,
                'image' => 'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=500',
                'category_id' => 2,
            ],
            [
                'name' => 'LG UltraWide 34" Monitor',
                'slug' => 'lg-ultrawide-34-monitor',
                'description' => '34-inch curved ultrawide monitor, 144Hz, QHD resolution',
                'price' => 599.00,
                'purchase_price' => 360.00,
                'discount_price' => 499.00,
                'stock' => 40,
                'sold_count' => 134,
                'rating' => 4.6,
                'featured' => false,
                'is_best_selling' => true,
                'is_latest' => false,
                'is_flash_sale' => true,
                'is_todays_deal' => true,
                'image' => 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500',
                'category_id' => 2,
            ],
            [
                'name' => 'Logitech MX Master 3S',
                'slug' => 'logitech-mx-master-3s',
                'description' => 'Premium wireless mouse with 8K DPI, quiet clicks',
                'price' => 99.00,
                'purchase_price' => 60.00,
                'discount_price' => 79.00,
                'stock' => 150,
                'sold_count' => 456,
                'rating' => 4.8,
                'featured' => false,
                'is_best_selling' => true,
                'is_latest' => false,
                'is_flash_sale' => false,
                'is_todays_deal' => true,
                'image' => 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500',
                'category_id' => 2,
            ],
            [
                'name' => 'Keychron K8 Pro Keyboard',
                'slug' => 'keychron-k8-pro-keyboard',
                'description' => 'Mechanical wireless keyboard with hot-swappable switches',
                'price' => 119.00,
                'purchase_price' => 70.00,
                'discount_price' => 99.00,
                'stock' => 85,
                'sold_count' => 267,
                'rating' => 4.7,
                'featured' => false,
                'is_best_selling' => false,
                'is_latest' => true,
                'is_flash_sale' => true,
                'is_todays_deal' => false,
                'image' => 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500',
                'category_id' => 2,
            ],
            [
                'name' => 'Samsung 2TB NVMe SSD',
                'slug' => 'samsung-2tb-nvme-ssd',
                'description' => 'Ultra-fast PCIe 4.0 SSD with 7000MB/s read speeds',
                'price' => 179.00,
                'purchase_price' => 110.00,
                'discount_price' => 149.00,
                'stock' => 120,
                'sold_count' => 345,
                'rating' => 4.9,
                'featured' => false,
                'is_best_selling' => true,
                'is_latest' => false,
                'is_flash_sale' => false,
                'is_todays_deal' => true,
                'image' => 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=500',
                'category_id' => 2,
            ],

            // Clothing Category (ID: 4) - 7 products
            [
                'name' => 'Nike Air Max 270 Sneakers',
                'slug' => 'nike-air-max-270-sneakers',
                'description' => 'Comfortable lifestyle sneakers with Max Air cushioning',
                'price' => 159.00,
                'purchase_price' => 95.00,
                'discount_price' => 129.00,
                'stock' => 200,
                'sold_count' => 523,
                'rating' => 4.6,
                'featured' => true,
                'is_best_selling' => true,
                'is_latest' => false,
                'is_flash_sale' => true,
                'is_todays_deal' => true,
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
                'category_id' => 4,
            ],
            [
                'name' => 'Levi\'s 501 Original Jeans',
                'slug' => 'levis-501-original-jeans',
                'description' => 'Classic straight fit denim jeans, button fly',
                'price' => 79.00,
                'purchase_price' => 47.00,
                'discount_price' => 59.00,
                'stock' => 180,
                'sold_count' => 678,
                'rating' => 4.7,
                'featured' => true,
                'is_best_selling' => true,
                'is_latest' => false,
                'is_flash_sale' => false,
                'is_todays_deal' => true,
                'image' => 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=500',
                'category_id' => 4,
            ],
            [
                'name' => 'Adidas Ultraboost 23',
                'slug' => 'adidas-ultraboost-23',
                'description' => 'Premium running shoes with Boost cushioning technology',
                'price' => 189.00,
                'purchase_price' => 113.00,
                'discount_price' => 149.00,
                'stock' => 90,
                'sold_count' => 312,
                'rating' => 4.8,
                'featured' => true,
                'is_best_selling' => true,
                'is_latest' => true,
                'is_flash_sale' => true,
                'is_todays_deal' => false,
                'image' => 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=500',
                'category_id' => 4,
            ],
            [
                'name' => 'North Face Puffer Jacket',
                'slug' => 'north-face-puffer-jacket',
                'description' => 'Warm insulated winter jacket, water-resistant',
                'price' => 299.00,
                'purchase_price' => 180.00,
                'discount_price' => 229.00,
                'stock' => 65,
                'sold_count' => 198,
                'rating' => 4.9,
                'featured' => false,
                'is_best_selling' => false,
                'is_latest' => true,
                'is_flash_sale' => false,
                'is_todays_deal' => true,
                'image' => 'https://images.unsplash.com/photo-1548126032-079b-97ebf8a5?w=500',
                'category_id' => 4,
            ],
            [
                'name' => 'Ray-Ban Aviator Sunglasses',
                'slug' => 'ray-ban-aviator-sunglasses',
                'description' => 'Classic aviator style sunglasses with UV protection',
                'price' => 159.00,
                'purchase_price' => 95.00,
                'discount_price' => 119.00,
                'stock' => 140,
                'sold_count' => 445,
                'rating' => 4.7,
                'featured' => false,
                'is_best_selling' => true,
                'is_latest' => false,
                'is_flash_sale' => true,
                'is_todays_deal' => false,
                'image' => 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500',
                'category_id' => 4,
            ],
            [
                'name' => 'Champion Hoodie',
                'slug' => 'champion-hoodie',
                'description' => 'Comfortable pullover hoodie with kangaroo pocket',
                'price' => 59.00,
                'purchase_price' => 35.00,
                'discount_price' => 39.00,
                'stock' => 250,
                'sold_count' => 789,
                'rating' => 4.5,
                'featured' => false,
                'is_best_selling' => true,
                'is_latest' => false,
                'is_flash_sale' => true,
                'is_todays_deal' => true,
                'image' => 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500',
                'category_id' => 4,
            ],
            [
                'name' => 'Timberland Boots',
                'slug' => 'timberland-boots',
                'description' => 'Durable waterproof leather boots for all seasons',
                'price' => 199.00,
                'purchase_price' => 120.00,
                'discount_price' => 159.00,
                'stock' => 75,
                'sold_count' => 234,
                'rating' => 4.8,
                'featured' => false,
                'is_best_selling' => false,
                'is_latest' => true,
                'is_flash_sale' => false,
                'is_todays_deal' => false,
                'image' => 'https://images.unsplash.com/photo-1605408499391-6368c628ef42?w=500',
                'category_id' => 4,
            ],

            // Books Category (ID: 7) - 6 products
            [
                'name' => 'Atomic Habits by James Clear',
                'slug' => 'atomic-habits-james-clear',
                'description' => 'Bestselling guide to building good habits and breaking bad ones',
                'price' => 27.00,
                'purchase_price' => 16.00,
                'discount_price' => 19.99,
                'stock' => 300,
                'sold_count' => 1245,
                'rating' => 4.9,
                'featured' => true,
                'is_best_selling' => true,
                'is_latest' => false,
                'is_flash_sale' => false,
                'is_todays_deal' => true,
                'image' => 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500',
                'category_id' => 7,
            ],
            [
                'name' => 'The Psychology of Money',
                'slug' => 'psychology-of-money',
                'description' => 'Timeless lessons on wealth, greed, and happiness',
                'price' => 25.00,
                'purchase_price' => 15.00,
                'discount_price' => 17.99,
                'stock' => 280,
                'sold_count' => 987,
                'rating' => 4.8,
                'featured' => true,
                'is_best_selling' => true,
                'is_latest' => false,
                'is_flash_sale' => true,
                'is_todays_deal' => false,
                'image' => 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=500',
                'category_id' => 7,
            ],
            [
                'name' => 'Project Hail Mary',
                'slug' => 'project-hail-mary',
                'description' => 'Sci-fi thriller by the author of The Martian',
                'price' => 29.00,
                'purchase_price' => 17.00,
                'discount_price' => 21.99,
                'stock' => 190,
                'sold_count' => 567,
                'rating' => 4.9,
                'featured' => false,
                'is_best_selling' => true,
                'is_latest' => true,
                'is_flash_sale' => false,
                'is_todays_deal' => true,
                'image' => 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500',
                'category_id' => 7,
            ],
            [
                'name' => 'Thinking, Fast and Slow',
                'slug' => 'thinking-fast-and-slow',
                'description' => 'Nobel Prize winner\'s insights into human decision making',
                'price' => 32.00,
                'purchase_price' => 19.00,
                'discount_price' => 24.99,
                'stock' => 220,
                'sold_count' => 834,
                'rating' => 4.7,
                'featured' => false,
                'is_best_selling' => true,
                'is_latest' => false,
                'is_flash_sale' => false,
                'is_todays_deal' => false,
                'image' => 'https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=500',
                'category_id' => 7,
            ],
            [
                'name' => 'Deep Work by Cal Newport',
                'slug' => 'deep-work-cal-newport',
                'description' => 'Rules for focused success in a distracted world',
                'price' => 28.00,
                'purchase_price' => 17.00,
                'discount_price' => 20.99,
                'stock' => 265,
                'sold_count' => 712,
                'rating' => 4.6,
                'featured' => false,
                'is_best_selling' => false,
                'is_latest' => false,
                'is_flash_sale' => true,
                'is_todays_deal' => true,
                'image' => 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=500',
                'category_id' => 7,
            ],
            [
                'name' => 'The Silent Patient',
                'slug' => 'the-silent-patient',
                'description' => 'Bestselling psychological thriller novel',
                'price' => 26.00,
                'purchase_price' => 15.50,
                'discount_price' => 18.99,
                'stock' => 340,
                'sold_count' => 1089,
                'rating' => 4.8,
                'featured' => true,
                'is_best_selling' => true,
                'is_latest' => false,
                'is_flash_sale' => false,
                'is_todays_deal' => true,
                'image' => 'https://images.unsplash.com/photo-1513001900722-370f803f498d?w=500',
                'category_id' => 7,
            ],

            // Home & Kitchen Category (ID: 8) - 7 products
            [
                'name' => 'Ninja Air Fryer XL',
                'slug' => 'ninja-air-fryer-xl',
                'description' => 'Large capacity air fryer with 6 cooking functions',
                'price' => 149.00,
                'purchase_price' => 90.00,
                'discount_price' => 99.00,
                'stock' => 85,
                'sold_count' => 456,
                'rating' => 4.7,
                'featured' => true,
                'is_best_selling' => true,
                'is_latest' => false,
                'is_flash_sale' => true,
                'is_todays_deal' => true,
                'image' => 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=500',
                'category_id' => 8,
            ],
            [
                'name' => 'Instant Pot Duo 7-in-1',
                'slug' => 'instant-pot-duo-7-in-1',
                'description' => 'Multi-cooker: pressure cooker, slow cooker, rice cooker, and more',
                'price' => 119.00,
                'purchase_price' => 72.00,
                'discount_price' => 79.00,
                'stock' => 110,
                'sold_count' => 678,
                'rating' => 4.8,
                'featured' => true,
                'is_best_selling' => true,
                'is_latest' => false,
                'is_flash_sale' => false,
                'is_todays_deal' => true,
                'image' => 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=500',
                'category_id' => 8,
            ],
            [
                'name' => 'Dyson V15 Cordless Vacuum',
                'slug' => 'dyson-v15-cordless-vacuum',
                'description' => 'Powerful cordless vacuum with laser detection',
                'price' => 649.00,
                'purchase_price' => 390.00,
                'discount_price' => 549.00,
                'stock' => 45,
                'sold_count' => 234,
                'rating' => 4.9,
                'featured' => true,
                'is_best_selling' => false,
                'is_latest' => true,
                'is_flash_sale' => true,
                'is_todays_deal' => false,
                'image' => 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=500',
                'category_id' => 8,
            ],
            [
                'name' => 'KitchenAid Stand Mixer',
                'slug' => 'kitchenaid-stand-mixer',
                'description' => 'Professional 5-quart stand mixer with 10 speeds',
                'price' => 429.00,
                'purchase_price' => 260.00,
                'discount_price' => 349.00,
                'stock' => 60,
                'sold_count' => 345,
                'rating' => 4.9,
                'featured' => false,
                'is_best_selling' => true,
                'is_latest' => false,
                'is_flash_sale' => false,
                'is_todays_deal' => true,
                'image' => 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=500',
                'category_id' => 8,
            ],
            [
                'name' => 'Nespresso Coffee Machine',
                'slug' => 'nespresso-coffee-machine',
                'description' => 'Compact espresso maker with milk frother',
                'price' => 199.00,
                'purchase_price' => 120.00,
                'discount_price' => 149.00,
                'stock' => 95,
                'sold_count' => 523,
                'rating' => 4.6,
                'featured' => false,
                'is_best_selling' => true,
                'is_latest' => false,
                'is_flash_sale' => true,
                'is_todays_deal' => true,
                'image' => 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=500',
                'category_id' => 8,
            ],
            [
                'name' => 'Le Creuset Dutch Oven',
                'slug' => 'le-creuset-dutch-oven',
                'description' => 'Premium enameled cast iron 5.5-quart dutch oven',
                'price' => 379.00,
                'purchase_price' => 228.00,
                'discount_price' => 299.00,
                'stock' => 40,
                'sold_count' => 167,
                'rating' => 4.9,
                'featured' => false,
                'is_best_selling' => false,
                'is_latest' => true,
                'is_flash_sale' => false,
                'is_todays_deal' => false,
                'image' => 'https://images.unsplash.com/photo-1584990347449-39e4c98d2a3c?w=500',
                'category_id' => 8,
            ],
            [
                'name' => 'iRobot Roomba j7+',
                'slug' => 'irobot-roomba-j7-plus',
                'description' => 'Smart robot vacuum with self-emptying base',
                'price' => 799.00,
                'purchase_price' => 480.00,
                'discount_price' => 649.00,
                'stock' => 30,
                'sold_count' => 189,
                'rating' => 4.7,
                'featured' => true,
                'is_best_selling' => false,
                'is_latest' => true,
                'is_flash_sale' => true,
                'is_todays_deal' => true,
                'image' => 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=500',
                'category_id' => 8,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
